[package]
name = "hipack"
version = "0.1.1"
authors = ["Adrian Perez de Castro <aperez@igalia.com>"]
repository = "https://github.com/aperezdc/hipack-rs"
license = "MIT/Apache-2.0"
description = "Serialization/deserialization for the HiPack format"
keywords = ["hipack", "serialization"]
